public class Rutas {

    public static void IrANiquia(MetroMedellin.Tren t) {
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
    }

    public static void rutaNiquia(MetroMedellin.Tren t) {
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
    }

    public static void IrAEstrella(MetroMedellin.Tren t) {

        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
    }

    public static void rutaEstrella(MetroMedellin.Tren t) {
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();

        t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
    }

    public static void IrASanJavier(MetroMedellin.Tren t) {
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
    }

    public static void rutaSanJavier(MetroMedellin.Tren t) {
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft(); t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();

        t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe(); t.moveSafe();
        t.turnRight();
        t.moveSafe(); t.moveSafe();
        t.turnLeft();
        t.moveSafe();
        t.turnLeft();
        t.moveSafe();
    }
}
