public class Rutas {

    public static void IrANiquia(MetroMedellin.Tren t) {
        t.move();
        t.turnLeft();
        t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
    }

    public static void rutaNiquia(MetroMedellin.Tren t) {
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move();
        t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
    }

    public static void IrAEstrella(MetroMedellin.Tren t) {
        t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
    }

    public static void rutaEstrella(MetroMedellin.Tren t) {
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move();

        t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
    }

    public static void IrASanJavier(MetroMedellin.Tren t) {
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
    }

    public static void rutaSanJavier(MetroMedellin.Tren t) {
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnRight();
        t.move();
        t.turnLeft(); t.turnLeft();
        t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move();

        t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
        t.move(); t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move();
        t.turnLeft();
        t.move(); t.move(); t.move(); t.move(); t.move();
        t.turnRight();
        t.move(); t.move();
        t.turnLeft();
        t.move();
        t.turnLeft();
        t.move();
    }
}
